name: "Issue Report | 报告问题"
description: "File a Issue report | 填写问题报告"
title: "[ISSUE]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing! Before we start, please read following guidelines carefully:
        感谢您的贡献！在开始前，请仔细阅读下述规则：
        
        - Be kind and respectful to each other, think about your family and if you wish them to see your post content.
        - 请尊重他人，想象一下你的近亲会如何对你的发言内容作出反应。
        
        - Ensure all discussion is related to the topic/goal of this repo.
        - 请确保话题内容与本代码库主题/目标存在关联，避免无关紧要的内容。
        
        - If you are not willing to contribute, respect the others who are willing to.
        - 如果您不打算作出贡献，请勿妨碍他人。
        
        - Internet is chaotic however open source community doesn't have to be, your post should demonstrate the education you receieved.
        - 互联网并非法外之地，请遵守您所在地的法律法规及 GitHub 使用条款，以体现您的个人涵养以及教育水平。
        
  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct ｜ 行为守则"
      description: | 
        Please ensure your issue adheres to the above guidelines.
        请确保提交问题前，您的内容遵守上述规则。
      options:
        - label: "I agree to follow this project's Code of Conduct | 我同意遵守规则"
          required: true
  - type: textarea
    id: content
    attributes:
      label: "Issue Description | 问题描述"
